### ISSUE TITLE
Add pls

### ISSUE THREAD

**Issue by Heyter** [thelastpenguin/GmodZ#1]
Add pls trade and shop npc. [Sell/Buy]

**Comment by Heyter** [comment]
Omg. How get 'you have full inventory' in server function
if inv:AddStack(stack) > then ... don't work.

**Comment by thelastpenguin** [comment]
@Heyter there's actually no function to check if it's full right now. The way the GM works I never really needed one though I see that its a pretty bad omission. If you'd like to add one to inventory meta sv.lua and pull request the changes that'd be awesome.

I'm talking with http://kraglestudios.com about picking up this project again since I've seen a bit of interest in it.

**Comment by Heyter** [comment]
I don't know how create function on check full inventory.
Fucking 3D panels.
Needed trade..
>I'm talking with http://kraglestudios.com about picking up this project again since I've seen a bit of interest in it.

Good. Interesting.

**Comment by Heyter** [comment]
FAS:2.0 attach. don't work with inventory.

**Comment by Heyter** [comment]
no save ammo, if weapon dropped.
no save wep. attachments, if weapon dropped.
more bugs :(

**Comment by Heyter** [comment]
I want this mod :(
https://www.youtube.com/watch?v=3SLBasyNE6E

**Comment by thelastpenguin** [comment]
@Heyter i merged in your pull request for this issue so I'll go ahead and close this! At the moment there's not much interest in picking it up within my group, but feel free to contact me on discord if you'd be interested in picking up the project.

**Comment by farman-beep** [comment]
Does this still work correctly, I tried it the other day but I got a huge influx of errors. I tried solving a few but it seems to be out of my league.

**Comment by Heyter** [comment]
@orcus1, Mod obsolete. So Bad.

**Comment by gareth-machine-user** [comment]
@Heyter @orcus1 yeah I've not maintained this code in a long time and I'm in college now so I mostly don't have time.

What kinds of errors were you getting?

**Comment by Heyter** [comment]
Stop using 3d panels.
If player die and inventory open, then inventory panel glitching.
